  - name: Install from apt
    apt: name={{ item }} state=present update_cache=yes
    with_items:
       - jetty
       - zip
       - unzip
       - openjdk-7-jdk
       - libjetty-extra
       - vim
       - curl

  - name: Downloading Solr if 
    get_url: url=http:{{ solr_repo }}/{{ solr_version }}/solr-{{ solr_version }}.tgz dest=/root/solr-{{ solr_version }}.tgz

  - name: Unzipping Solr
    command: tar zxf /root/solr-{{ solr_version }}.tgz -C /root/ 

  - name: Creating the Solr dir
    command: mkdir /usr/share/solr creates=/usr/share/solr
  - file: path=/usr/share/solr recurse=yes owner=jetty group=jetty

  - name: Unzip Solr
    command: unzip /root/solr-{{ solr_version }}/dist/solr-{{ solr_version }}.war -d /usr/share/solr

  - name: Copy Solr libs
    command: rsync -arvz /root/solr-{{ solr_version }}/example/lib/ext/ /usr/share/jetty/lib/ext/

  - name: Symlink
    file: src=/usr/share/solr path=/usr/share/jetty/webapps/solr state=link

  - name: Set up solr config
    template: src=config/solr.xml dest=/usr/share/solr/solr.xml

  - name: Jetty config so we can start it
    template: src=config/jetty dest=/etc/default/jetty

  - name: Creating the lib dir
    command: mkdir -p /var/lib/solr/kc/data
  - file: path=/var/lib/solr recurse=yes owner=jetty group=jetty

  - name: Creating the core dir
    command: mkdir -p /usr/share/solr/kc owner=jetty group=jetty
  - name: Copy the conf for the core
    command: cp -r /root/solr-{{ solr_version }}/example/solr/collection1/conf /usr/share/solr/kc owner=jetty group=jetty

  - name: Copy the needed jar in the right path
    command: cp /root/solr-{{ solr_version }}/example/lib/ext/log4j-1.2.16.jar /usr/share/solr/WEB-INF/lib/

  - name: Copy the needed jars
    command: /bin/cp /root/solr-{{ solr_version }}/example/lib/ext/slf4j-api-1.6.6.jar /usr/share/solr/WEB-INF/lib/

  - name: Copy the needed jars
    command: /bin/cp /root/solr-{{ solr_version }}/example/lib/ext/slf4j-log4j12-1.6.6.jar /usr/share/solr/WEB-INF/lib/

  - name: Download the Drupal config for Solr
    get_url: url={{ drupal_solr_repo  }}-{{ drupal_solr_version }}.zip dest=/root/search_api_solr-{{ drupal_solr_version }}.zip

  - name: Unzipping it
    command: unzip /root/search_api_solr-{{ drupal_solr_version }}.zip -d /root/
  
  - name: Creating the folder kc
    command: mkdir /usr/share/solr/kc/conf

  - name: Copy the configs to the core
    command: rsync -arvz /root/search_api_solr/solr-conf/4.x/ /usr/share/solr/kc/conf/
  - file: path=/usr/share/solr/kc recurse=yes owner=jetty group=jetty
    notify: restart Jetty
